version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:
    image: mariadb:10.4.30
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  app:
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
